Update run-inputs & info errors
0xPolygonHermez/zkevm-proverjs pull request #128
Opened 2023-01-23 12:46 UTC by laisolizq

- Add errors info `proverjs`
- Update `run-inputs`: add new flags & test-ooc options

2023-01-24 16:47 UTC, krlosMata requested changes

2023-01-24 16:47 UTC, krlosMata commented on src/sm/sm_main/sm_main_exec.js
> +    nameRomErrors = []
I think this line is not needed

2023-01-25 11:53 UTC, krlosMata approved these changes
:smile_cat:

2023-01-25 12:53 UTC, zkronos73 approved these changes

2023-01-25 13:58 UTC, merged