New database 2
0xPolygonHermez/zkevm-proverjs pull request #150
Opened 2023-02-15 09:16 UTC by ignasirv

The MemDB class (from the commonjs repository) has been replaced with the new Database class. This new database class supports connections to a PostgreSQL database. Anyway, the default behavior of the database class (calling only the constructor) is to use only a "memory" database in the same way that the MemDB class works.

To connect to a PostGreSQL database, you must call the Database.connection(connectionString, dbTable) function and specify the connection string to the PostGreSQL database. Optionally, you can specify the name of the table to store the data (default is "state.merkletree");

For easy of implementation and use of the Database class, if you specify "local" as connectionString, then only "memory" db (as MemDB class) will be used .

Two new optional arguments has been added to the main_executor.js:

[-D/--databaseURL] -> connection string to the PostGreSQL DB (if this argument is not specified, it defaults to "local")
[-n/--dbnodestable] -> name of the table used for nodes
[-G/--dbprogramtable] -> name of the table used for programs
Examples:
main_executor ...... -D postgresql://statedb:statedb@127.0.0.1:5432/testdb
main_executor ...... -D postgresql://statedb:statedb@127.0.0.1:5432/testdb -T state.merkletree

2023-02-15 10:19 UTC, krlosMata approved these changes
:smile_cat:

2023-02-15 15:44 UTC, zkronos73 requested changes
before merge this PR, need to resolve a previous PR that it introduces a new way to add command options compatibles with config file.

2023-02-15 15:55 UTC, ignasirv commented
Which PR?

2023-02-16 11:10 UTC, zkronos73 approved these changes

2023-02-16 11:20 UTC, merged