Feature/pairings complex addition
0xPolygonHermez/zkevm-proverjs pull request #196
Opened 2023-05-31 09:23 UTC by zkronos73

2023-05-31 10:25 UTC, hecmas approved these changes

2023-06-01 15:19 UTC, laisolizq approved these changes

2023-06-07 14:52 UTC, laisolizq requested changes

2023-06-07 14:52 UTC, laisolizq commented on src/sm/sm_main/sm_main_exec.js
> +                const _x3 = Fec.sub(Fec.mul(s, s), Fec.add(Fe.e(x1), dbl ? Fec.e(x1) : Fec.e(x2)));
`Fe.` --> `Fec.`

2023-06-07 15:05 UTC, laisolizq approved these changes

2023-06-07 15:06 UTC, merged